version: "3.9"

services:
  mongodb:
    image: mongo 
    container_name: mongodb 
    ports:
      - "27017:27017"
    networks:
      - app-network 

  web-app:
    build: ./web-app
    container_name: theonepiece-web-app 
    depends_on:
      - mongodb 
    networks:
      - app-network 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/theonepiece 
    ports:
      - "5000:5000"
    command: python app.py
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /web-app

networks:
  app-network:
    driver: bridge 
