version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=theonepiece

  web-app:
    build: ./web-app
    container_name: theonepiece-web-app
    depends_on:
      - mongodb 
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/theonepiece?authSource=admin
    ports:
      - "5000:5000"
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /web-app

networks:
  app-network:
    driver: bridge
