version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  web-app:
    build: ./web-app
    container_name: theonepiece-web-app
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/theonepiece  # MongoDB connection URI
    ports:
      - "5000:5000"  # Expose the Flask app to the host
    command: python app.py  # Command to run the Flask app

networks:
  app-network:
    driver: bridge
