name: Continuous Deployment to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/CD.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/CD.yml'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull and Push MongoDB Image
      run: |
        # Pull the official MongoDB image
        docker pull mongo:latest
        # Tag the MongoDB image for your repository
        docker tag mongo:latest ${{ secrets.DOCKER_HUB_USERNAME }}/theonepiece:mongo-latest
        # Push the MongoDB image to Docker Hub
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/theonepiece:mongo-latest

    - name: Build and Push Web App Image
      run: |
        # Build the web-app service using docker-compose
        docker-compose build web-app
        # Tag the web-app image for your repository
        docker tag theonepiece-web-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/theonepiece:web-app-latest
        # Push the web-app image to Docker Hub
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/theonepiece:web-app-latest
