name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd web-app
          pip install pipenv
          pipenv install --dev

      - name: Run tests with coverage
        env:
          MONGO_CXN_STRING: mongodb://localhost:27017/
        run: |
          # Activate pipenv shell and run tests from the root directory
          cd web-app
          pipenv run pytest ../web-app/test_app.py --cov=../web-app --cov-report=xml
          pipenv run coverage report -m

      - name: Build Docker image
        run: |
          docker build -t web-app \
            --build-arg MONGO_CXN_STRING=mongodb://localhost:27017/ \
            ./web-app
